// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdXLgXysB8d9F1_Pn-bzSmEWxSV6dJRJ8',
    appId: '1:31030399602:web:4fc8e710895a0f5ce668eb',
    messagingSenderId: '31030399602',
    projectId: 'studgpt-486c7',
    authDomain: 'studgpt-486c7.firebaseapp.com',
    databaseURL: 'https://studgpt-486c7-default-rtdb.firebaseio.com',
    storageBucket: 'studgpt-486c7.firebasestorage.app',
    measurementId: 'G-ZFQ887HE4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNs6BuZ5eDmkO1h8rehuXXr5rIe21-zk',
    appId: '1:31030399602:android:bc2f71432093dc99e668eb',
    messagingSenderId: '31030399602',
    projectId: 'studgpt-486c7',
    databaseURL: 'https://studgpt-486c7-default-rtdb.firebaseio.com',
    storageBucket: 'studgpt-486c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPPYR2guA2hjZsTnFLZbECc-NfVKDy1Xk',
    appId: '1:31030399602:ios:d3f3e5c48b439b8de668eb',
    messagingSenderId: '31030399602',
    projectId: 'studgpt-486c7',
    databaseURL: 'https://studgpt-486c7-default-rtdb.firebaseio.com',
    storageBucket: 'studgpt-486c7.firebasestorage.app',
    androidClientId: '31030399602-n9lask0aagq9encj0rjq8onuoi9np44k.apps.googleusercontent.com',
    iosClientId: '31030399602-v9ediga5kbme3t516md5n9eqtv8sbq1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.studgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPPYR2guA2hjZsTnFLZbECc-NfVKDy1Xk',
    appId: '1:31030399602:ios:d3f3e5c48b439b8de668eb',
    messagingSenderId: '31030399602',
    projectId: 'studgpt-486c7',
    databaseURL: 'https://studgpt-486c7-default-rtdb.firebaseio.com',
    storageBucket: 'studgpt-486c7.firebasestorage.app',
    androidClientId: '31030399602-n9lask0aagq9encj0rjq8onuoi9np44k.apps.googleusercontent.com',
    iosClientId: '31030399602-v9ediga5kbme3t516md5n9eqtv8sbq1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.studgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdXLgXysB8d9F1_Pn-bzSmEWxSV6dJRJ8',
    appId: '1:31030399602:web:186c25020f59c70ce668eb',
    messagingSenderId: '31030399602',
    projectId: 'studgpt-486c7',
    authDomain: 'studgpt-486c7.firebaseapp.com',
    databaseURL: 'https://studgpt-486c7-default-rtdb.firebaseio.com',
    storageBucket: 'studgpt-486c7.firebasestorage.app',
    measurementId: 'G-GWK9BMKNWL',
  );
}
